"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import circle

class TestCircleDraw( unittest.TestCase ):

    def setUp( self ):
        self.expected_x = 333
        self.expected_y = 444
        self.expected_dx = 11
        self.expected_dy = 22
        self.expected_rotation = 45
        self.expected_radius = 23
        self.expected_world_width = 600
        self.expected_world_height = 800
        self.expected_color = ( 255, 255, 255 )
        
        self.constructed_obj = circle.Circle( self.expected_x, self.expected_y, self.expected_dx, self.expected_dy, self.expected_rotation, self.expected_radius, self.expected_world_width, self.expected_world_height )
        
        return

    def tearDown( self ):
        return

    def test001_circleHasDraw( self ):
        self.assertEqual( hasattr( self.constructed_obj, 'draw' ), True )
        return

    
def suite( ):
    return unittest.TestLoader( ).loadTestsFromTestCase( TestCircleDraw )

if __name__ == '__main__':
    runner = unittest.TextTestRunner( )
    runner.run( suite( ) )
