"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import movable

class TestMovableActive( unittest.TestCase ):

    def setUp( self ):
        self.expected_x = 100
        self.expected_y = 200
        self.expected_dx = 1.5
        self.expected_dy = -2.5
        self.expected_world_width = 600
        self.expected_world_height = 400

        self.constructed_movable = movable.Movable( self.expected_x, self.expected_y, self.expected_dx, self.expected_dy, self.expected_world_width, self.expected_world_height )
        
        return

    def tearDown( self ):
        return

    def test001_setsActive( self ):
        expected_active = True
        self.constructed_movable.setActive( expected_active )
        self.assertEqual( self.constructed_movable.getActive( ), expected_active )
        return
    
    def test002_setsNotActive( self ):
        expected_active = False
        self.constructed_movable.setActive( expected_active )
        self.assertEqual( self.constructed_movable.getActive( ), expected_active )
        return
    
    
def suite( ):
    return unittest.TestLoader( ).loadTestsFromTestCase( TestMovableActive )

if __name__ == '__main__':
    runner = unittest.TextTestRunner( )
    runner.run( suite( ) )
