"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
Do Not Move on to the next function until its tests report 'ok' or your code
may not work as expected.
"""

import unittest

def suite( ):
    test_modules = [ 
        "test_001_movable_000_all",
        "test_002_rotatable_000_all",
        "test_003_polygon_000_all",
        "test_004_ship_000_all",
        "test_005_rock_000_all",
        "test_006_circle_000_all",
        "test_007_bullet_000_all",
        "test_008_star_000_all",
        "test_009_asteroids_000_all",
    ]

    s = unittest.TestSuite( )
    for m in test_modules:
        s.addTest( __import__(m ).suite( ) )
        
    return s
        
if __name__ == '__main__':
    runner = unittest.TextTestRunner( )
    runner.run( suite( ) )
    print( "Part 2 Unit Tests do not test all of the Asteriods class." )
